export interface Question {
  id: number
  question: string
  options: { id: string; text: string }[]
  correctAnswer: string
  multipleAnswers: boolean
  note?: string
}

export const questions: Question[] = [
  {
    id: 1,
    question:
      "Which documents does SAP Transportation Management support when planning transportation with SAP S/4HANA?",
    options: [
      { id: "A", text: "Material documents" },
      { id: "B", text: "Stock transport orders" },
      { id: "C", text: "Transfer orders" },
      { id: "D", text: "Inbound deliveries" },
      { id: "E", text: "Returns" },
    ],
    correctAnswer: "B, D, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 2,
    question: "What is the result of posting a vendor's invoice?",
    options: [
      { id: "A", text: "The material ledger document is generated" },
      { id: "B", text: "The vendor's account is cleared of open items." },
      { id: "C", text: "The purchase order history is updated." },
      { id: "D", text: "Vendor payment is posted" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 3,
    question: "For which object do you plan activity prices?",
    options: [
      { id: "A", text: "Cost center" },
      { id: "B", text: "Work center" },
      { id: "C", text: "WBS element" },
      { id: "D", text: "Internal order" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 4,
    question:
      "You've been tasked with converting SAP Fiori Tile groups to SAP Fiori Spaces. Which of the following assignments should be made?",
    options: [
      { id: "A", text: "Assign Tiles to Pages" },
      { id: "B", text: "Assign Spaces to Pages" },
      { id: "C", text: "Assign Pages to Spaces" },
      { id: "D", text: "Assign Sections to Spaces" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 5,
    question: "What is created when you post a valuated goods receipt for consumable materials?",
    options: [
      { id: "A", text: "Material ledger document" },
      { id: "B", text: "Vendor invoice document" },
      { id: "C", text: "Controlling document" },
      { id: "D", text: "Commitment" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 6,
    question: "Which of the following is the basic organizational unit in Management Accounting?",
    options: [
      { id: "A", text: "Cost Center" },
      { id: "B", text: "Client" },
      { id: "C", text: "Company Code" },
      { id: "D", text: "Controlling Area" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 7,
    question: "You post an invoice to purchase a company car. What accounts are posted in the journal entry?",
    options: [
      { id: "A", text: "Supplier account" },
      { id: "B", text: "Asset account" },
      { id: "C", text: "Material account" },
      { id: "D", text: "Tax account" },
      { id: "E", text: "Customer account" },
    ],
    correctAnswer: "A, B, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 8,
    question:
      "Which of the following is a permitted hierarchical structure for Management Accounting in the SAP S/4HANA enterprise structure?",
    options: [
      { id: "A", text: "A controlling area is assigned to a plant." },
      { id: "B", text: "A controlling area is assigned to an operating concern." },
      { id: "C", text: "An operating concern is assigned to a company code." },
      { id: "D", text: "An operating concern is assigned to a controlling area." },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 9,
    question: "Why might you create an equipment master record?",
    options: [
      { id: "A", text: "To report the usage time of an object at a functional location" },
      {
        id: "B",
        text: "To perform and record maintenance tasks for certain parts of your technical system for long-term evaluation",
      },
      { id: "C", text: "To functionally represent the technical system structures at your company" },
      { id: "D", text: "To collect and evaluate technical data for an object over a long period of time" },
    ],
    correctAnswer: "B, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 10,
    question: "What is the result of document splitting?",
    options: [
      { id: "A", text: "Additional logistical documents are created" },
      { id: "B", text: "Additional controlling documents are created" },
      { id: "C", text: "Additional values are created" },
      { id: "D", text: "Additional financial documents are created" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 11,
    question: "What are some of the functions of SAP Extended Warehouse Management?",
    options: [
      { id: "A", text: "Putaway with transfer orders" },
      { id: "B", text: "Mobile device integration" },
      { id: "C", text: "Storage-bin-level determination for incoming goods" },
      { id: "D", text: "Inventory management at storage location level" },
    ],
    correctAnswer: "B, C",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 12,
    question: "Which object is created to report on market characteristics, such as customer, product, and region?",
    options: [
      { id: "A", text: "Sales organization" },
      { id: "B", text: "Profit center" },
      { id: "C", text: "Profitability segment" },
      { id: "D", text: "Segment" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 13,
    question: "What must you do in a purchase order to purchase a material for a cost center?",
    options: [
      { id: "A", text: "Enter a purchase order item category" },
      { id: "B", text: "Enter a storage location." },
      { id: "C", text: "Enter an activity type for the cost center in the purchasing document." },
      { id: "D", text: "Enter an account assignment category" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 14,
    question:
      "You have found a new source of supply for a material. When maintaining the Business Partner information for the Supplier role, which organizational unit should be extended?",
    options: [
      { id: "A", text: "Purchasing Organization" },
      { id: "B", text: "Company Code" },
      { id: "C", text: "Plant" },
      { id: "D", text: "Purchasing Group" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 15,
    question: "What type of document is generated for an external network activity?",
    options: [
      { id: "A", text: "Production order" },
      { id: "B", text: "Sales order" },
      { id: "C", text: "Reservation" },
      { id: "D", text: "Purchase requisition" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 16,
    question: "What general ledger accounts receive postings when performing the goods receipt?",
    options: [
      { id: "A", text: "Vendor reconciliation account" },
      { id: "B", text: "Tax Account" },
      { id: "C", text: "Consumption account" },
      { id: "D", text: "GR/IR account" },
    ],
    correctAnswer: "A, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 17,
    question:
      "In a project, what is the correct term for a group of dependencies, activities, and relationships sequenced in chronological order?",
    options: [
      { id: "A", text: "Work breakdown structure" },
      { id: "B", text: "Project planning" },
      { id: "C", text: "Routing" },
      { id: "D", text: "Network" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 18,
    question: "Which of the following applies to Sales and Distribution enterprise structures?",
    options: [
      { id: "A", text: "A division can only be assigned to one sales organization." },
      { id: "B", text: "A sales organization can only be assigned to one company code" },
      { id: "C", text: "A sales organization can be assigned to more than one company code." },
      { id: "D", text: "A distribution channel can be assigned to many sales organizations." },
      { id: "E", text: "A division can be assigned to more than one sales organization." },
    ],
    correctAnswer: "B, D, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 19,
    question: "What activities can an employee complete using employee self-service?",
    options: [
      { id: "A", text: "Enroll in a training course" },
      { id: "B", text: "Perform compensation planning" },
      { id: "C", text: "Enter work times" },
      { id: "D", text: "Recruit employees" },
      { id: "E", text: "Update banking information" },
    ],
    correctAnswer: "A, C, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 20,
    question: "What are some of the characteristics of the SAP Fiori UX design?",
    options: [
      { id: "A", text: "Function-based applications" },
      { id: "B", text: "Role-based applications" },
      { id: "C", text: "Adaptive to devices" },
      { id: "D", text: "Multiple access entry points" },
    ],
    correctAnswer: "B, C",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 21,
    question: "What are the integration points between a fixed asset and a cost center?",
    options: [
      { id: "A", text: "Asset creation" },
      { id: "B", text: "Asset acquisition" },
      { id: "C", text: "Asset book value" },
      { id: "D", text: "Depreciation run" },
    ],
    correctAnswer: "A, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 22,
    question: "What can a successful MRP run create?",
    options: [
      { id: "A", text: "Dependent requirements" },
      { id: "B", text: "Purchase orders" },
      { id: "C", text: "Reservations" },
      { id: "D", text: "Planned independent requirements" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 23,
    question: "How can you post internal labor costs to a network activity?",
    options: [
      { id: "A", text: "By activity allocation" },
      { id: "B", text: "By distribution" },
      { id: "C", text: "By confirmation" },
      { id: "D", text: "By service entry sheet" },
    ],
    correctAnswer: "A, C",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 24,
    question: "What action assigns actual costs to a project?",
    options: [
      { id: "A", text: "Material availability check" },
      { id: "B", text: "Saving a purchase order" },
      { id: "C", text: "Material withdrawal from stock" },
      { id: "D", text: "Releasing a project budget" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 25,
    question:
      "You purchase raw materials with a purchase order against a cost center. During which process step are financial accounting documents posted?",
    options: [
      { id: "A", text: "Save purchase order" },
      { id: "B", text: "Approval of purchase requisition" },
      { id: "C", text: "Inbound delivery to warehouse" },
      { id: "D", text: "Post valuated goods receipt" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 26,
    question: "Which SAP Suite line-of-business solution can be used to enhance the procurement of external services?",
    options: [
      { id: "A", text: "SAP Ariba" },
      { id: "B", text: "SAP Concur Travel and Expense" },
      { id: "C", text: "SAP SuccessFactors" },
      { id: "D", text: "SAP Fieldglass" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 27,
    question: "What does a work center control?",
    options: [
      { id: "A", text: "Availability of capacity" },
      { id: "B", text: "Calculation of costs of work performed" },
      { id: "C", text: "Release of production orders" },
      { id: "D", text: "Valuation of bill of material components" },
    ],
    correctAnswer: "A, B",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 28,
    question: "What are the benefits of using a business partner in SAP S/4HANA?",
    options: [
      { id: "A", text: "Vendors are managed separately from customers." },
      { id: "B", text: "Redundant data is reduced." },
      { id: "C", text: "Data architecture is harmonized" },
      { id: "D", text: "General data is unique to each assigned role." },
    ],
    correctAnswer: "B, C",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 29,
    question: "In a warehouse, what represents the physical location where the goods are stored?",
    options: [
      { id: "A", text: "Plant" },
      { id: "B", text: "Storage Bin" },
      { id: "C", text: "Storage Type" },
      { id: "D", text: "Storage Location" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
  {
    id: 30,
    question:
      "You have created an equipment master record. What other master data record can be created automatically?",
    options: [
      { id: "A", text: "Functional location" },
      { id: "B", text: "Material" },
      { id: "C", text: "Asset" },
      { id: "D", text: "Maintenance BOM" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 31,
    question: "Which action updates the costing-based profitability analysis?",
    options: [
      { id: "A", text: "Post goods issue" },
      { id: "B", text: "Save the billing document" },
      { id: "C", text: "Post the customer's payment" },
      { id: "D", text: "Create the outbound delivery" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
  {
    id: 32,
    question: "Which of the following are advantages of the SAP Business Technology Platform?",
    options: [
      { id: "A", text: "Unified application development environment" },
      { id: "B", text: "Optimized for any software" },
      { id: "C", text: "Uses the latest machine learning innovations" },
      { id: "D", text: "Uses SAP Fiori Spaces" },
      { id: "E", text: "Flexible workflows" },
    ],
    correctAnswer: "A, C, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 33,
    question: "Which of the following can be maintained in a maintenance notification?",
    options: [
      { id: "A", text: "Materials planning" },
      { id: "B", text: "Capacity requirements" },
      { id: "C", text: "Tasks" },
      { id: "D", text: "Cause of damage" },
      { id: "E", text: "Equipment" },
    ],
    correctAnswer: "C, D, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 34,
    question: "What is the purpose of using a Work Breakdown Structure (WBS)?",
    options: [
      { id: "A", text: "To evaluate aggregated data" },
      { id: "B", text: "To schedule warehouse tasks" },
      { id: "C", text: "To manage equipment" },
      { id: "D", text: "To allocate budgets" },
      { id: "E", text: "To define responsibilities" },
    ],
    correctAnswer: "A, D, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 35,
    question: "What elements are recorded during an overall completion confirmation of a maintenance order?",
    options: [
      { id: "A", text: "Time entry" },
      { id: "B", text: "Measuring documents" },
      { id: "C", text: "Availability check" },
      { id: "D", text: "Materials" },
      { id: "E", text: "Invoicing" },
    ],
    correctAnswer: "A, B, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 36,
    question: "What tasks are performed for external reporting purposes?",
    options: [
      { id: "A", text: "Manage accounts receivables" },
      { id: "B", text: "Calculate production variances" },
      { id: "C", text: "Create a profit and loss statement" },
      { id: "D", text: "Create cost center plan/actual statements" },
    ],
    correctAnswer: "C, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 37,
    question: "What business partner role connects the supplier with your company code's balance sheet?",
    options: [
      { id: "A", text: "FI Vendor" },
      { id: "B", text: "Business Partner General" },
      { id: "C", text: "FI Customer" },
      { id: "D", text: "Supplier" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 38,
    question: "What is the timeframe of SAP SuccessFactors release cycles?",
    options: [
      { id: "A", text: "Bi-annually" },
      { id: "B", text: "Monthly" },
      { id: "C", text: "Annually" },
      { id: "D", text: "Quarterly" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 39,
    question: "To what object can you settle an internal order?",
    options: [
      { id: "A", text: "Statistical key figure" },
      { id: "B", text: "Equipment" },
      { id: "C", text: "Profit center" },
      { id: "D", text: "Fixed asset" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 40,
    question:
      "When running MRP, what setting in the material master determines if a material will be procured or produced?",
    options: [
      { id: "A", text: "Procurement type" },
      { id: "B", text: "Purchasing group" },
      { id: "C", text: "MRP type" },
      { id: "D", text: "Processing key" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 41,
    question: "What transactions credit a production order?",
    options: [
      { id: "A", text: "Goods receipt" },
      { id: "B", text: "Material withdrawal" },
      { id: "C", text: "Confirmation" },
      { id: "D", text: "Order settlement" },
    ],
    correctAnswer: "A, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 42,
    question: "Which organizational units do you create for Financial Accounting (FI) in SAP S/4HANA Finance?",
    options: [
      { id: "A", text: "Operating concern" },
      { id: "B", text: "Controlling area" },
      { id: "C", text: "Segment" },
      { id: "D", text: "Company code" },
    ],
    correctAnswer: "B, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 43,
    question: "During the production order process, what steps can be executed via background processing?",
    options: [
      { id: "A", text: "Order release" },
      { id: "B", text: "Order settlement" },
      { id: "C", text: "WIP determination" },
      { id: "D", text: "Order confirmation" },
      { id: "E", text: "Order creation" },
    ],
    correctAnswer: "A, B, C",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 44,
    question: "Which controlling object is always a statistical object?",
    options: [
      { id: "A", text: "Internal order" },
      { id: "B", text: "Profitability segment" },
      { id: "C", text: "Cost center" },
      { id: "D", text: "Profit center" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
  {
    id: 45,
    question: "When creating condition master records, what data properties does the condition type control?",
    options: [
      { id: "A", text: "Scales" },
      { id: "B", text: "Validity period" },
      { id: "C", text: "Currency" },
      { id: "D", text: "Sales organization" },
    ],
    correctAnswer: "A, B",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 46,
    question: "Which application shows the current levels of stock, requirements, and receipts for a given material?",
    options: [
      { id: "A", text: "MRP Live" },
      { id: "B", text: "MRP List" },
      { id: "C", text: "Stock overview" },
      { id: "D", text: "Stock requirements list" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 47,
    question: "Which master records are directly assigned to a company code?",
    options: [
      { id: "A", text: "Material" },
      { id: "B", text: "Cost center" },
      { id: "C", text: "Activity type" },
      { id: "D", text: "Fixed asset" },
    ],
    correctAnswer: "B, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 48,
    question:
      "When creating a warehouse number in the SAP enterprise structure, what organizational elements must be assigned?",
    options: [
      { id: "A", text: "Shipping point" },
      { id: "B", text: "Company code" },
      { id: "C", text: "Plant" },
      { id: "D", text: "Storage location" },
    ],
    correctAnswer: "C, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 49,
    question: "In a warehouse, what represents the physical location where the goods are stored?",
    options: [
      { id: "A", text: "Pallet" },
      { id: "B", text: "Storage location" },
      { id: "C", text: "Storage section" },
      { id: "D", text: "Storage bin" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 50,
    question: "What objects are used to create a Purchasing Info Record?",
    options: [
      { id: "A", text: "Company code" },
      { id: "B", text: "Purchasing organization" },
      { id: "C", text: "Material master" },
      { id: "D", text: "Vendor" },
      { id: "E", text: "Purchasing group" },
    ],
    correctAnswer: "B, C, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 51,
    question: "Which objects can you settle?",
    options: [
      { id: "A", text: "Work breakdown structure (WBS) element" },
      { id: "B", text: "Maintenance order" },
      { id: "C", text: "Profitability segment" },
      { id: "D", text: "Cost center" },
    ],
    correctAnswer: "A, B, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 52,
    question: "Which of the following is the hierarchical model of a project?",
    options: [
      { id: "A", text: "Task list" },
      { id: "B", text: "Work breakdown structure" },
      { id: "C", text: "Network" },
      { id: "D", text: "Activity" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
  {
    id: 53,
    question:
      "Which processes can be automatically performed when you post an order confirmation for a production order?",
    options: [
      { id: "A", text: "Variance calculation" },
      { id: "B", text: "Order settlement" },
      { id: "C", text: "Goods issue" },
      { id: "D", text: "Goods receipt" },
      { id: "E", text: "Post actual costs" },
    ],
    correctAnswer: "B, C, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 54,
    question:
      "You are creating a new company code that you want to assign to the group controlling area. Which characteristics must the new company code share with the other company codes already assigned to the controlling area?",
    options: [
      { id: "A", text: "Posting period variant" },
      { id: "B", text: "Fiscal year variant" },
      { id: "C", text: "Operating chart of accounts" },
      { id: "D", text: "Group currency" },
    ],
    correctAnswer: "B, C",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 55,
    question: "What are the suite qualities of the SAP Intelligent Enterprise?",
    options: [
      { id: "A", text: "One workflow inbox" },
      { id: "B", text: "End-to-end process blueprints" },
      { id: "C", text: "Embedded analytics per product" },
      { id: "D", text: "Seamless user experience" },
      { id: "E", text: "Code-based applications" },
    ],
    correctAnswer: "B, C, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 56,
    question: "Which business process activities create a Financial Accounting (FI) document?",
    options: [
      { id: "A", text: "Transfer stock from storage location to storage location" },
      { id: "B", text: "Post goods issue to a production order" },
      { id: "C", text: "Execute a depreciation run" },
      { id: "D", text: "Create a sales order" },
      { id: "E", text: "Transfer stock to another company code" },
    ],
    correctAnswer: "B, C, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 57,
    question: "What demand elements are evaluated during a MRP run?",
    options: [
      { id: "A", text: "Sales orders" },
      { id: "B", text: "Planned orders" },
      { id: "C", text: "Scheduled lines" },
      { id: "D", text: "Purchase requisitions" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 58,
    question: "What happens when you post a goods issue in a delivery document for a sales order?",
    options: [
      { id: "A", text: "An EWM outbound delivery order is created." },
      { id: "B", text: "The billing due list is updated" },
      { id: "C", text: "An invoice is created" },
      { id: "D", text: "A material ledger document is created." },
      { id: "E", text: "Inventory quantities are updated." },
    ],
    correctAnswer: "A, B, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 59,
    question: "What function commits funds assigned to the budget of a WBS element?",
    options: [
      { id: "A", text: "Availability control" },
      { id: "B", text: "Cost center accounting" },
      { id: "C", text: "Settlement processing" },
      { id: "D", text: "Profitability analysis" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 60,
    question: "Which controlling objects can be settled by a settlement rule in SAP S/4HANA?",
    options: [
      { id: "A", text: "Production order" },
      { id: "B", text: "Maintenance order" },
      { id: "C", text: "WBS element" },
      { id: "D", text: "Sales order" },
      { id: "E", text: "Profit center" },
    ],
    correctAnswer: "A, B, C",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 61,
    question: "When is backorder processing considered?",
    options: [
      { id: "A", text: "When goods issue is performed" },
      { id: "B", text: "When order quantity is not fully confirmed" },
      { id: "C", text: "When planning transportation" },
      { id: "D", text: "When advanced available-to-promise is unavailable" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
  {
    id: 62,
    question:
      "Which backorder processing (BOP) strategy has first processing priority and is used to release confirmed stock to prioritize other orders to plan future stock needs?",
    options: [
      { id: "A", text: "Lose" },
      { id: "B", text: "Gain" },
      { id: "C", text: "Win" },
      { id: "D", text: "Fill" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 63,
    question: "Why would you enter your working hours using Cross-Application Time Sheet (CATS)?",
    options: [
      { id: "A", text: "To record overtime" },
      { id: "B", text: "To request absence" },
      { id: "C", text: "To confirm activities" },
      { id: "D", text: "To maintain absence" },
      { id: "E", text: "To plan time" },
    ],
    correctAnswer: "A, C, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 64,
    question: "Which objects can be assigned to a profit center?",
    options: [
      { id: "A", text: "Sales order item" },
      { id: "B", text: "Purchase order item" },
      { id: "C", text: "Sales organization" },
      { id: "D", text: "Material" },
    ],
    correctAnswer: "A, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 65,
    question: "What is the result of converting a planned order?",
    options: [
      { id: "A", text: "A planned independent requirement" },
      { id: "B", text: "A purchase requisition" },
      { id: "C", text: "A purchase order" },
      { id: "D", text: "A production order" },
    ],
    correctAnswer: "B, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 66,
    question: "What is a typical sequence of process steps in corrective maintenance?",
    options: [
      {
        id: "A",
        text: "Create task list → Create notification → Schedule notification → Release order → Confirm order",
      },
      { id: "B", text: "Create notification → Plan order → Execute order → Complete order → Confirm order" },
      { id: "C", text: "Create notification → Plan order → Release order → Confirm order → Complete order" },
      {
        id: "D",
        text: "Create task list → Create notification → Schedule notification → Confirm order → Complete order",
      },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 67,
    question:
      "In the enterprise structure, what Human Resources organizational element is assigned directly to a company code?",
    options: [
      { id: "A", text: "Personnel area" },
      { id: "B", text: "Position" },
      { id: "C", text: "Infotype" },
      { id: "D", text: "Organizational unit" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 68,
    question: "What does a posting key control?",
    options: [
      { id: "A", text: "Debit/credit posting" },
      { id: "B", text: "Posting without tax allowed" },
      { id: "C", text: "Number range of document" },
      { id: "D", text: "Account type" },
    ],
    correctAnswer: "A, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 69,
    question: "Which of the following are business partner categories in SAP S/4HANA?",
    options: [
      { id: "A", text: "Individual" },
      { id: "B", text: "Group" },
      { id: "C", text: "Person" },
      { id: "D", text: "Corporation" },
      { id: "E", text: "Organization" },
    ],
    correctAnswer: "B, C, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 70,
    question: "Which of the following are selection modes for running MRP?",
    options: [
      { id: "A", text: "MRP Live" },
      { id: "B", text: "Predictive MRP" },
      { id: "C", text: "Classical MRP" },
      { id: "D", text: "Regenerative MRP" },
      { id: "E", text: "Backorder Processing" },
    ],
    correctAnswer: "A, C, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 71,
    question:
      "You are creating a new company code that you want to assign to the group controlling area. Which characteristics must the new company code share with the other company codes already assigned to the controlling area?",
    options: [
      { id: "A", text: "Fiscal year variant" },
      { id: "B", text: "Operating chart of accounts" },
      { id: "C", text: "Currency" },
      { id: "D", text: "Posting period variant" },
    ],
    correctAnswer: "A, B",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 72,
    question: "What information do you maintain for a general ledger account on company code level?",
    options: [
      { id: "A", text: "Account group" },
      { id: "B", text: "Account type" },
      { id: "C", text: "Account number" },
      { id: "D", text: "Account currency" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 73,
    question: "What is one advantage of using stock transport orders instead of stock transfers?",
    options: [
      { id: "A", text: "The ownership transfer and carrier delivery costs are delayed until goods receipt" },
      { id: "B", text: "Goods movements occur in one step, only at goods issue." },
      { id: "C", text: "The purchase orders that are generated by MRP can be converted to stock transport orders" },
      {
        id: "D",
        text: "The process of goods issue and goods receipt is monitored using the purchase order (PO) history",
      },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 74,
    question: "What technology elements supercharge the human experience when working with X and O data?",
    options: [
      { id: "A", text: "Machine learning predictions" },
      { id: "B", text: "Internet of Things (IoT)" },
      { id: "C", text: "Blockchain" },
      { id: "D", text: "Conversational AI" },
    ],
    correctAnswer: "A, B",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 75,
    question: "What occurs when a maintenance technician changes the status of an order to technically completed?",
    options: [
      { id: "A", text: "A time entry is posted for the maintenance technician." },
      { id: "B", text: "Incoming invoices for the order can be processed" },
      { id: "C", text: "Open purchase requisitions are marked for deletion." },
      { id: "D", text: "Reserved materials are released from the reservation." },
      { id: "E", text: "The order's settlement rule is executed." },
    ],
    correctAnswer: "B, C, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 76,
    question: "What master data in the activity type is used to post an activity allocation?",
    options: [
      { id: "A", text: "Cost element" },
      { id: "B", text: "Internal order" },
      { id: "C", text: "WBS element" },
      { id: "D", text: "Statistical key figure" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 77,
    question:
      "In a make-to-order process, a raw material needs to be issued from the warehouse to the manufacturing line. To which order will you post the goods issue?",
    options: [
      { id: "A", text: "Outbound delivery order" },
      { id: "B", text: "Production order" },
      { id: "C", text: "Stock transport order" },
      { id: "D", text: "Sales order" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
  {
    id: 78,
    question: "What data must be linked to a cost center to derive segment accounting?",
    options: [
      { id: "A", text: "Profit center" },
      { id: "B", text: "Cost center category" },
      { id: "C", text: "General ledger account" },
      { id: "D", text: "Controlling area" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 79,
    question: "Which SAP Fiori application types use SAP HANA capabilities directly?",
    options: [
      { id: "A", text: "Analytical" },
      { id: "B", text: "Transactional" },
      { id: "C", text: "SAP GUI for HTML" },
      { id: "D", text: "Fact sheet" },
    ],
    correctAnswer: "A, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 80,
    question: "What occurs when planning an internal project activity?",
    options: [
      { id: "A", text: "Costs are recorded" },
      { id: "B", text: "Service is performed." },
      { id: "C", text: "Purchase requisitions are generated." },
      { id: "D", text: "Resources are committed" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 81,
    question: "What document, when saved, creates a commitment for an internal order?",
    options: [
      { id: "A", text: "Maintenance order" },
      { id: "B", text: "Production order" },
      { id: "C", text: "Goods receipt" },
      { id: "D", text: "Purchase order" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 82,
    question: "What maintenance order elements are included in an operation?",
    options: [
      { id: "A", text: "Object list" },
      { id: "B", text: "Settlement rule" },
      { id: "C", text: "Work center" },
      { id: "D", text: "Standard time" },
      { id: "E", text: "Activity type" },
    ],
    correctAnswer: "A, C, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 83,
    question:
      "Which end-to-end business processes are included with SAP S/4HANA in the context of the Intelligent Enterprise?",
    options: [
      { id: "A", text: "Order to cash" },
      { id: "B", text: "Request to service" },
      { id: "C", text: "Source to pay" },
      { id: "D", text: "Design to build" },
      { id: "E", text: "Record to report" },
    ],
    correctAnswer: "A, C, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 84,
    question:
      "You want the SAP S/4HANA system to perform product cost planning. What master data is used to calculate the quantity structure?",
    options: [
      { id: "A", text: "Routing" },
      { id: "B", text: "Work center" },
      { id: "C", text: "Cost center" },
      { id: "D", text: "Bill of material" },
    ],
    correctAnswer: "A, D",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 85,
    question: "At which steps in the order-to-cash process are postings made to the general ledger (G/L)?",
    options: [
      { id: "A", text: "Creating a sales order" },
      { id: "B", text: "Posting a goods issue" },
      { id: "C", text: "Saving an invoice" },
      { id: "D", text: "Creating an outbound delivery" },
    ],
    correctAnswer: "B, C",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 86,
    question: "A goods issue is posted against a production order. What are the results?",
    options: [
      { id: "A", text: "A warehouse task is created." },
      { id: "B", text: "The material reservation is reduced." },
      { id: "C", text: "Internal labor costs are posted." },
      { id: "D", text: "A material ledger document is created" },
      { id: "E", text: "Actual costs are updated in the production order." },
    ],
    correctAnswer: "B, D, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 87,
    question: "To which application areas can Cross-Application Time Sheet (CATS) data be transferred directly?",
    options: [
      { id: "A", text: "Management Accounting (CO)" },
      { id: "B", text: "Human Capital Management (HCM)" },
      { id: "C", text: "Project System (PS)" },
      { id: "D", text: "Financial Accounting (FI)" },
      { id: "E", text: "Production Planning (PP)" },
    ],
    correctAnswer: "A, B, C",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 88,
    question: "In what step of the purchase-to-pay process is a purchase requisition generated?",
    options: [
      { id: "A", text: "Determination of requirements" },
      { id: "B", text: "Source of supply determination" },
      { id: "C", text: "Vendor selection" },
      { id: "D", text: "Invoice verification" },
    ],
    correctAnswer: "A",
    multipleAnswers: false,
  },
  {
    id: 89,
    question: "In a project, what is linked via relationships?",
    options: [
      { id: "A", text: "Work breakdown structure elements" },
      { id: "B", text: "Networks" },
      { id: "C", text: "Activities" },
      { id: "D", text: "Project definitions" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 90,
    question: "How do you view all records created for an employee?",
    options: [
      { id: "A", text: "Basic personal data" },
      { id: "B", text: "Personnel action" },
      { id: "C", text: "Organizational assignment" },
      { id: "D", text: "Personnel file" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 91,
    question: "How can you post external labour costs to a network activity?",
    options: [
      { id: "A", text: "By activity allocation" },
      { id: "B", text: "By service entry sheet" },
      { id: "C", text: "By settlement" },
      { id: "D", text: "By confirmation" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
  {
    id: 92,
    question: "What types of procedures may be used to perform a cross-plant stock transfer?",
    options: [
      { id: "A", text: "Stock transport order without delivery" },
      { id: "B", text: "Slotting and rearrangement" },
      { id: "C", text: "Two-step procedure" },
      { id: "D", text: "One-step procedure" },
      { id: "E", text: "Material requirements planning" },
    ],
    correctAnswer: "A, C, D",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 93,
    question: "What activities can a manager complete using Manager Self-Service?",
    options: [
      { id: "A", text: "Control costs" },
      { id: "B", text: "Enroll in benefits" },
      { id: "C", text: "Enter time sheet" },
      { id: "D", text: "Manage budget" },
    ],
    correctAnswer: "B, C",
    multipleAnswers: true,
    note: "There are 2 correct answers to this question",
  },
  {
    id: 94,
    question: "What planning tool prioritizes sales order forecasting and strategically plans inventory buffers?",
    options: [
      { id: "A", text: "MRP simulation and resolution" },
      { id: "B", text: "Demand-driven MRP (DDMRP)" },
      { id: "C", text: "Constraint-based planning (PP/DS)" },
      { id: "D", text: "Backorder processing (BOP)" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
  {
    id: 95,
    question: "When you post an accounting document, for which line item must you enter a transaction type?",
    options: [
      { id: "A", text: "Tax account" },
      { id: "B", text: "Material account" },
      { id: "C", text: "Customer account" },
      { id: "D", text: "Asset account" },
    ],
    correctAnswer: "D",
    multipleAnswers: false,
  },
  {
    id: 96,
    question: "How do you use the result of a released standard cost estimate?",
    options: [
      { id: "A", text: "To determine a material sales price in Sales and Distribution" },
      { id: "B", text: "To calculate the price of an activity type" },
      { id: "C", text: "To determine the base costs used to calculate overhead" },
      { id: "D", text: "To calculate the plan costs in a production order" },
      { id: "E", text: "To update the current standard price in the material master record" },
    ],
    correctAnswer: "B, D, E",
    multipleAnswers: true,
    note: "There are 3 correct answers to this question",
  },
  {
    id: 97,
    question: "What must you do in a purchase order to purchase a material for a cost center?",
    options: [
      { id: "A", text: "Enter a purchase order item category" },
      { id: "B", text: "Enter an account assignment category" },
      { id: "C", text: "Change the account to a cost element" },
      { id: "D", text: "Change the material type appropriately" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
  {
    id: 98,
    question: "Where do you maintain primary and secondary cost elements?",
    options: [
      { id: "A", text: "Cost Element Accounting" },
      { id: "B", text: "Profit Center Accounting" },
      { id: "C", text: "General Ledger Accounting" },
      { id: "D", text: "Cost Center Accounting" },
    ],
    correctAnswer: "C",
    multipleAnswers: false,
  },
  {
    id: 99,
    question: "Which document is created when you post a valuated goods receipt for consumable materials?",
    options: [
      { id: "A", text: "Delivery note" },
      { id: "B", text: "Controlling document" },
      { id: "C", text: "Vendor invoice document" },
      { id: "D", text: "Purchase order" },
    ],
    correctAnswer: "B",
    multipleAnswers: false,
  },
]
